server:
  port: ${JENKINS_SERVICE_PORT}
spring:
  data:
    mongodb:
      uri: ${DATABASE_URI}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: constancy-java-client
            authorization-grant-type: authorizatoin_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/constancy
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/constancy
constancy:
  jenkins:
    service:
      connection:
        timeout-milliseconds: 30_000
