server:
  port: ${JENKINS_SERVICE_PORT}
spring:
  data:
    mongodb:
      uri: ${DATABASE_URI}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: constancy-java-client
            client-secret: vkTuFJnINZWs2IUdaiErEKQmUwrz6pMG
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/constancy
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/constancy
constancy:
  front-end-url: http://localhost:4200
  jenkins:
    service:
      url: http://localhost:8082
      connection:
        timeout-milliseconds: 30_000
